USE EarthNew
GO

SET TRANSACTION ISOLATION LEVEL READ COMMITTED -- Solution TRANSACTION ISOLATION LEVEL REPEATABLE READ-

BEGIN TRANSACTION
	SELECT * FROM Professions
	GO
	WAITFOR DELAY '00:00:07';
	SELECT * FROM Professions;
	GO
COMMIT TRANSACTION;

