USE EarthNew
GO

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ -- Solution: TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
	SELECT * FROM Professions;
	GO
	WAITFOR DELAY '00:00:05';
	SELECT * FROM Professions;
	GO
COMMIT TRANSACTION;
GO
